### ISSUE TITLE
写了个小功能，问下作者同不同意

### ISSUE THREAD

**Issue by Mikky574** [JimouChen/auto-youth-study#1]
我写了个在每周一或者周二的随机一个非凌晨（0点到6点）的时间内运行fun1函数，其他时间sleep的脚本。一周只会运行一次。
要不我pr个上来？

**Comment by Mikky574** [comment]
o ,刚注意到有实现类似的了。打扰了23333

**Comment by JimouChen** [comment]
- 要做定时任务的话，你可以参考[这个👈](https://github.com/JimouChen/auto-youth-study-gd)哦，只需要修改这个schedule即可

 ```
  schedule:
    - cron: '0 5 * * *'
```

**Comment by Mikky574** [comment]
看到了，谢谢
